apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - dragonfly.yaml
  - hpa.yaml

patches:
  - target:
      kind: Deployment
      name: course-app-deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
  
  - target:
      kind: Deployment
      name: course-app-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

  - target:
      kind: ConfigMap
      name: course-app-map
    patch: |-
      - op: replace
        path: /data/APP_REDIS_URL
        value: "redis://dragonfly-prod:6379"

  - target:
      kind: Ingress
      name: ingress-course-app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: course-app-prod.127.0.0.1.sslip.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: course-app-prod.127.0.0.1.sslip.io