apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
  - namespace.yaml
  - ../../base
  - dragonfly.yaml

patches:
  - target:
      kind: Deployment
      name: course-app-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: ConfigMap
      name: course-app-map
    patch: |-
      - op: replace
        path: /data/APP_REDIS_URL
        value: "redis://dragonfly-dev:6379"